### ISSUE TITLE
DDPLS stürzt ab bei cast to Text

### ISSUE THREAD

**Issue by Magi3r** [DDP-Projekt/DDPLS#1]
DDPLS stürzt ab, wenn ich die einen Ausdruck, der einen Buchstaben zurückgibt,  zu einem Text konvertiere. Der Fehler tritt nicht auf, wenn die konvertierung schon beim Start vom Language Server im code steht, nur, wenn sie zur Laufzeit von DDPLS geändert wird.

<details><summary>Fehlermeldung</summary>
<p>
panic: interface conversion: ddptypes.Type is nil, not ddptypes.PrimitiveType [recovered]
	panic: ParserError(Mod: /home/Magi3r/Documents/AoC-2023/05a.ddp): unknown parser panic
Wraps: interface conversion: ddptypes.Type is nil, not ddptypes.PrimitiveType
StackTrace:
goroutine 7 [running]:
runtime/debug.Stack()
	/usr/local/go/src/runtime/debug/stack.go:24 +0x65
github.com/DDP-Projekt/Kompilierer/src/parser.parser_panic_wrapper(0xc00067edd0)
	/home/bafto/go/pkg/mod/github.com/!d!d!p-!projekt/!kompilierer@v0.0.1-alpha.0.20231202103202-571eaedc3dde/src/parser/error.go:35 +0x65
panic({0x662e00, 0xc00023c360})
	/usr/local/go/src/runtime/panic.go:884 +0x213
github.com/DDP-Projekt/Kompilierer/src/ast/typechecker.(*Typechecker).VisitCastExpr(0xc000692f90, 0xc00072a900)
	/home/bafto/go/pkg/mod/github.com/!d!d!p-!projekt/!kompilierer@v0.0.1-alpha.0.20231202103202-571eaedc3dde/src/ast/typechecker/typechecker.go:425 +0xd34
github.com/DDP-Projekt/Kompilierer/src/ast.(*CastExpr).Accept(0x65dae0?, {0x725310?, 0xc000692f90?})
	/home/bafto/go/pkg/mod/github.com/!d!d!p-!projekt/!kompilierer@v0.0.1-alpha.0.20231202103202-571eaedc3dde/src/ast/ast.go:424 +0x2a
github.com/DDP-Projekt/Kompilierer/src/ast/typechecker.(*Typechecker).visit(...)
	/home/bafto/go/pkg/mod/github.com/!d!d!p-!projekt/!kompilierer@v0.0.1-alpha.0.20231202103202-571eaedc3dde/src/ast/typechecker/typechecker.go:49
github.com/DDP-Projekt/Kompilierer/src/ast/typechecker.(*Typechecker).Evaluate(...)
	/home/bafto/go/pkg/mod/github.com/!d!d!p-!projekt/!kompilierer@v0.0.1-alpha.0.20231202103202-571eaedc3dde/src/ast/typechecker/typechecker.go:54
github.com/DDP-Projekt/Kompilierer/src/ast/typechecker.(*Typechecker).VisitVarDecl(0xc000692f90, 0xc000448140)
	/home/bafto/go/pkg/mod/github.com/!d!d!p-!projekt/!kompilierer@v0.0.1-alpha.0.20231202103202-571eaedc3dde/src/ast/typechecker/typechecker.go:106 +0x75
github.com/DDP-Projekt/Kompilierer/src/ast.(*VarDecl).Accept(0xc000692f60?, {0x725310?, 0xc000692f90?})
	/home/bafto/go/pkg/mod/github.com/!d!d!p-!projekt/!kompilierer@v0.0.1-alpha.0.20231202103202-571eaedc3dde/src/ast/ast.go:194 +0x2d
github.com/DDP-Projekt/Kompilierer/src/ast/typechecker.(*Typechecker).VisitDeclStmt(0x67da40?, 0x0?)
	/home/bafto/go/pkg/mod/github.com/!d!d!p-!projekt/!kompilierer@v0.0.1-alpha.0.20231202103202-571eaedc3dde/src/ast/typechecker/typechecker.go:527 +0x2e
github.com/DDP-Projekt/Kompilierer/src/ast.(*DeclStmt).Accept(0x0?, {0x725310?, 0xc000692f90?})
	/home/bafto/go/pkg/mod/github.com/!d!d!p-!projekt/!kompilierer@v0.0.1-alpha.0.20231202103202-571eaedc3dde/src/ast/ast.go:580 +0x2a
github.com/DDP-Projekt/Kompilierer/src/ast/typechecker.(*Typechecker).TypecheckNode(...)
	/home/bafto/go/pkg/mod/github.com/!d!d!p-!projekt/!kompilierer@v0.0.1-alpha.0.20231202103202-571eaedc3dde/src/ast/typechecker/typechecker.go:44
github.com/DDP-Projekt/Kompilierer/src/parser.(*parser).checkStatement(0xc00067edd0, {0x7224f8, 0xc00068ebf0?})
	/home/bafto/go/pkg/mod/github.com/!d!d!p-!projekt/!kompilierer@v0.0.1-alpha.0.20231202103202-571eaedc3dde/src/parser/parser.go:262 +0xe6
github.com/DDP-Projekt/Kompilierer/src/parser.(*parser).checkedDeclaration(0xc00067edd0)
	/home/bafto/go/pkg/mod/github.com/!d!d!p-!projekt/!kompilierer@v0.0.1-alpha.0.20231202103202-571eaedc3dde/src/parser/parser.go:268 +0x3d
github.com/DDP-Projekt/Kompilierer/src/parser.(*parser).blockStatement(0xc00067edd0, 0xc00068ebd0)
	/home/bafto/go/pkg/mod/github.com/!d!d!p-!projekt/!kompilierer@v0.0.1-alpha.0.20231202103202-571eaedc3dde/src/parser/parser.go:1652 +0x2a6
github.com/DDP-Projekt/Kompilierer/src/parser.(*parser).whileStatement(0xc00067edd0)
	/home/bafto/go/pkg/mod/github.com/!d!d!p-!projekt/!kompilierer@v0.0.1-alpha.0.20231202103202-571eaedc3dde/src/parser/parser.go:1377 +0x5b1
github.com/DDP-Projekt/Kompilierer/src/parser.(*parser).statement(0xc00067edd0)
	/home/bafto/go/pkg/mod/github.com/!d!d!p-!projekt/!kompilierer@v0.0.1-alpha.0.20231202103202-571eaedc3dde/src/parser/parser.go:1047 +0x52b
github.com/DDP-Projekt/Kompilierer/src/parser.(*parser).declaration(0xc00067edd0)
	/home/bafto/go/pkg/mod/github.com/!d!d!p-!projekt/!kompilierer@v0.0.1-alpha.0.20231202103202-571eaedc3dde/src/parser/parser.go:308 +0x3aa
github.com/DDP-Projekt/Kompilierer/src/parser.(*parser).checkedDeclaration(0xc00067edd0)
	/home/bafto/go/pkg/mod/github.com/!d!d!p-!projekt/!kompilierer@v0.0.1-alpha.0.20231202103202-571eaedc3dde/src/parser/parser.go:266 +0x1e
github.com/DDP-Projekt/Kompilierer/src/parser.(*parser).blockStatement(0xc00067edd0, 0xc00068eb60)
	/home/bafto/go/pkg/mod/github.com/!d!d!p-!projekt/!kompilierer@v0.0.1-alpha.0.20231202103202-571eaedc3dde/src/parser/parser.go:1652 +0x2a6
github.com/DDP-Projekt/Kompilierer/src/parser.(*parser).whileStatement(0xc00067edd0)
	/home/bafto/go/pkg/mod/github.com/!d!d!p-!projekt/!kompilierer@v0.0.1-alpha.0.20231202103202-571eaedc3dde/src/parser/parser.go:1377 +0x5b1
github.com/DDP-Projekt/Kompilierer/src/parser.(*parser).statement(0xc00067edd0)
	/home/bafto/go/pkg/mod/github.com/!d!d!p-!projekt/!kompilierer@v0.0.1-alpha.0.20231202103202-571eaedc3dde/src/parser/parser.go:1047 +0x52b
github.com/DDP-Projekt/Kompilierer/src/parser.(*parser).declaration(0xc00067edd0)
	/home/bafto/go/pkg/mod/github.com/!d!d!p-!projekt/!kompilierer@v0.0.1-alpha.0.20231202103202-571eaedc3dde/src/parser/parser.go:308 +0x3aa
github.com/DDP-Projekt/Kompilierer/src/parser.(*parser).checkedDeclaration(0xc00067edd0)
	/home/bafto/go/pkg/mod/github.com/!d!d!p-!projekt/!kompilierer@v0.0.1-alpha.0.20231202103202-571eaedc3dde/src/parser/parser.go:266 +0x1e
github.com/DDP-Projekt/Kompilierer/src/parser.(*parser).parse(0xc00067edd0)
	/home/bafto/go/pkg/mod/github.com/!d!d!p-!projekt/!kompilierer@v0.0.1-alpha.0.20231202103202-571eaedc3dde/src/parser/parser.go:122 +0xa5
github.com/DDP-Projekt/Kompilierer/src/parser.Parse({{0xc00001d6e7, 0x27}, {0xc00053ca00, 0x21fc, 0x2500}, {0xc000598000, 0x5b7, 0x78e}, 0xc000692d80, 0xc000302db0})
	/home/bafto/go/pkg/mod/github.com/!d!d!p-!projekt/!kompilierer@v0.0.1-alpha.0.20231202103202-571eaedc3dde/src/parser/interface.go:76 +0x2d7
github.com/DDP-Projekt/DDPLS/documents.(*DocumentState).reParseInContext(0xc000071b60, 0xc000692d80, 0xc000302db0)
	/home/bafto/source/repos/GoRepos/DDP-Projekt/DDPLS/documents/documents.go:58 +0x1b8
github.com/DDP-Projekt/DDPLS/documents.(*DocumentManager).reParse(0xc000411d30, {0xc00001d6e0, 0x2e}, 0x2e?)
	/home/bafto/source/repos/GoRepos/DDP-Projekt/DDPLS/documents/documents.go:111 +0x1a6
github.com/DDP-Projekt/DDPLS/documents.(*DocumentManager).Get(0xc000411d30, {0xc00001d3b0?, 0x16?})
	/home/bafto/source/repos/GoRepos/DDP-Projekt/DDPLS/documents/documents.go:123 +0x186
github.com/DDP-Projekt/DDPLS/handlers.CreateTextDocumentDidChange.func1(0xc0000db440, 0xc000692cc0)
	/home/bafto/source/repos/GoRepos/DDP-Projekt/DDPLS/handlers/sync.go:24 +0x5a
github.com/tliron/glsp/protocol_3_16.(*Handler).Handle(0xc000178b40, 0xc0000db440)
	/home/bafto/go/pkg/mod/github.com/bafto/glsp@v0.1.2-0.20230806091905-942e1aee0810/protocol_3_16/handler.go:320 +0x1567
github.com/tliron/glsp/server.(*Server).handle(0xc0000716e0, {0x721e68?, 0xc0000aa000}, 0xc00014ac60, 0xc0004b6ba0)
	/home/bafto/go/pkg/mod/github.com/bafto/glsp@v0.1.2-0.20230806091905-942e1aee0810/server/handle.go:46 +0x2b0
github.com/sourcegraph/jsonrpc2.(*HandlerWithErrorConfigurer).Handle(0xc000194040, {0x721e68, 0xc0000aa000}, 0xc00014ac60, 0xc0004b6ba0)
	/home/bafto/go/pkg/mod/github.com/sourcegraph/jsonrpc2@v0.2.0/handler_with_error.go:21 +0x63
github.com/sourcegraph/jsonrpc2.(*Conn).readMessages(0xc00014ac60, {0x721e68, 0xc0000aa000})
	/home/bafto/go/pkg/mod/github.com/sourcegraph/jsonrpc2@v0.2.0/conn.go:205 +0x26f
created by github.com/sourcegraph/jsonrpc2.NewConn
	/home/bafto/go/pkg/mod/github.com/sourcegraph/jsonrpc2@v0.2.0/conn.go:62 +0x2aa
 [recovered]
	panic: ParserError(Mod: /home/Magi3r/Documents/AoC-2023/05a.ddp): unknown parser panic
Wraps: interface conversion: ddptypes.Type is nil, not ddptypes.PrimitiveType
StackTrace:
goroutine 7 [running]:
runtime/debug.Stack()
	/usr/local/go/src/runtime/debug/stack.go:24 +0x65
github.com/DDP-Projekt/Kompilierer/src/parser.parser_panic_wrapper(0xc00067edd0)
	/home/bafto/go/pkg/mod/github.com/!d!d!p-!projekt/!kompilierer@v0.0.1-alpha.0.20231202103202-571eaedc3dde/src/parser/error.go:35 +0x65
panic({0x662e00, 0xc00023c360})
	/usr/local/go/src/runtime/panic.go:884 +0x213
github.com/DDP-Projekt/Kompilierer/src/ast/typechecker.(*Typechecker).VisitCastExpr(0xc000692f90, 0xc00072a900)
	/home/bafto/go/pkg/mod/github.com/!d!d!p-!projekt/!kompilierer@v0.0.1-alpha.0.20231202103202-571eaedc3dde/src/ast/typechecker/typechecker.go:425 +0xd34
github.com/DDP-Projekt/Kompilierer/src/ast.(*CastExpr).Accept(0x65dae0?, {0x725310?, 0xc000692f90?})
	/home/bafto/go/pkg/mod/github.com/!d!d!p-!projekt/!kompilierer@v0.0.1-alpha.0.20231202103202-571eaedc3dde/src/ast/ast.go:424 +0x2a
github.com/DDP-Projekt/Kompilierer/src/ast/typechecker.(*Typechecker).visit(...)
	/home/bafto/go/pkg/mod/github.com/!d!d!p-!projekt/!kompilierer@v0.0.1-alpha.0.20231202103202-571eaedc3dde/src/ast/typechecker/typechecker.go:49
github.com/DDP-Projekt/Kompilierer/src/ast/typechecker.(*Typechecker).Evaluate(...)
	/home/bafto/go/pkg/mod/github.com/!d!d!p-!projekt/!kompilierer@v0.0.1-alpha.0.20231202103202-571eaedc3dde/src/ast/typechecker/typechecker.go:54
github.com/DDP-Projekt/Kompilierer/src/ast/typechecker.(*Typechecker).VisitVarDecl(0xc000692f90, 0xc000448140)
	/home/bafto/go/pkg/mod/github.com/!d!d!p-!projekt/!kompilierer@v0.0.1-alpha.0.20231202103202-571eaedc3dde/src/ast/typechecker/typechecker.go:106 +0x75
github.com/DDP-Projekt/Kompilierer/src/ast.(*VarDecl).Accept(0xc000692f60?, {0x725310?, 0xc000692f90?})
	/home/bafto/go/pkg/mod/github.com/!d!d!p-!projekt/!kompilierer@v0.0.1-alpha.0.20231202103202-571eaedc3dde/src/ast/ast.go:194 +0x2d
github.com/DDP-Projekt/Kompilierer/src/ast/typechecker.(*Typechecker).VisitDeclStmt(0x67da40?, 0x0?)
	/home/bafto/go/pkg/mod/github.com/!d!d!p-!projekt/!kompilierer@v0.0.1-alpha.0.20231202103202-571eaedc3dde/src/ast/typechecker/typechecker.go:527 +0x2e
github.com/DDP-Projekt/Kompilierer/src/ast.(*DeclStmt).Accept(0x0?, {0x725310?, 0xc000692f90?})
	/home/bafto/go/pkg/mod/github.com/!d!d!p-!projekt/!kompilierer@v0.0.1-alpha.0.20231202103202-571eaedc3dde/src/ast/ast.go:580 +0x2a
github.com/DDP-Projekt/Kompilierer/src/ast/typechecker.(*Typechecker).TypecheckNode(...)
	/home/bafto/go/pkg/mod/github.com/!d!d!p-!projekt/!kompilierer@v0.0.1-alpha.0.20231202103202-571eaedc3dde/src/ast/typechecker/typechecker.go:44
github.com/DDP-Projekt/Kompilierer/src/parser.(*parser).checkStatement(0xc00067edd0, {0x7224f8, 0xc00068ebf0?})
	/home/bafto/go/pkg/mod/github.com/!d!d!p-!projekt/!kompilierer@v0.0.1-alpha.0.20231202103202-571eaedc3dde/src/parser/parser.go:262 +0xe6
github.com/DDP-Projekt/Kompilierer/src/parser.(*parser).checkedDeclaration(0xc00067edd0)
	/home/bafto/go/pkg/mod/github.com/!d!d!p-!projekt/!kompilierer@v0.0.1-alpha.0.20231202103202-571eaedc3dde/src/parser/parser.go:268 +0x3d
github.com/DDP-Projekt/Kompilierer/src/parser.(*parser).blockStatement(0xc00067edd0, 0xc00068ebd0)
	/home/bafto/go/pkg/mod/github.com/!d!d!p-!projekt/!kompilierer@v0.0.1-alpha.0.20231202103202-571eaedc3dde/src/parser/parser.go:1652 +0x2a6
github.com/DDP-Projekt/Kompilierer/src/parser.(*parser).whileStatement(0xc00067edd0)
	/home/bafto/go/pkg/mod/github.com/!d!d!p-!projekt/!kompilierer@v0.0.1-alpha.0.20231202103202-571eaedc3dde/src/parser/parser.go:1377 +0x5b1
github.com/DDP-Projekt/Kompilierer/src/parser.(*parser).statement(0xc00067edd0)
	/home/bafto/go/pkg/mod/github.com/!d!d!p-!projekt/!kompilierer@v0.0.1-alpha.0.20231202103202-571eaedc3dde/src/parser/parser.go:1047 +0x52b
github.com/DDP-Projekt/Kompilierer/src/parser.(*parser).declaration(0xc00067edd0)
	/home/bafto/go/pkg/mod/github.com/!d!d!p-!projekt/!kompilierer@v0.0.1-alpha.0.20231202103202-571eaedc3dde/src/parser/parser.go:308 +0x3aa
github.com/DDP-Projekt/Kompilierer/src/parser.(*parser).checkedDeclaration(0xc00067edd0)
	/home/bafto/go/pkg/mod/github.com/!d!d!p-!projekt/!kompilierer@v0.0.1-alpha.0.20231202103202-571eaedc3dde/src/parser/parser.go:266 +0x1e
github.com/DDP-Projekt/Kompilierer/src/parser.(*parser).blockStatement(0xc00067edd0, 0xc00068eb60)
	/home/bafto/go/pkg/mod/github.com/!d!d!p-!projekt/!kompilierer@v0.0.1-alpha.0.20231202103202-571eaedc3dde/src/parser/parser.go:1652 +0x2a6
github.com/DDP-Projekt/Kompilierer/src/parser.(*parser).whileStatement(0xc00067edd0)
	/home/bafto/go/pkg/mod/github.com/!d!d!p-!projekt/!kompilierer@v0.0.1-alpha.0.20231202103202-571eaedc3dde/src/parser/parser.go:1377 +0x5b1
github.com/DDP-Projekt/Kompilierer/src/parser.(*parser).statement(0xc00067edd0)
	/home/bafto/go/pkg/mod/github.com/!d!d!p-!projekt/!kompilierer@v0.0.1-alpha.0.20231202103202-571eaedc3dde/src/parser/parser.go:1047 +0x52b
github.com/DDP-Projekt/Kompilierer/src/parser.(*parser).declaration(0xc00067edd0)
	/home/bafto/go/pkg/mod/github.com/!d!d!p-!projekt/!kompilierer@v0.0.1-alpha.0.20231202103202-571eaedc3dde/src/parser/parser.go:308 +0x3aa
github.com/DDP-Projekt/Kompilierer/src/parser.(*parser).checkedDeclaration(0xc00067edd0)
	/home/bafto/go/pkg/mod/github.com/!d!d!p-!projekt/!kompilierer@v0.0.1-alpha.0.20231202103202-571eaedc3dde/src/parser/parser.go:266 +0x1e
github.com/DDP-Projekt/Kompilierer/src/parser.(*parser).parse(0xc00067edd0)
	/home/bafto/go/pkg/mod/github.com/!d!d!p-!projekt/!kompilierer@v0.0.1-alpha.0.20231202103202-571eaedc3dde/src/parser/parser.go:122 +0xa5
github.com/DDP-Projekt/Kompilierer/src/parser.Parse({{0xc00001d6e7, 0x27}, {0xc00053ca00, 0x21fc, 0x2500}, {0xc000598000, 0x5b7, 0x78e}, 0xc000692d80, 0xc000302db0})
	/home/bafto/go/pkg/mod/github.com/!d!d!p-!projekt/!kompilierer@v0.0.1-alpha.0.20231202103202-571eaedc3dde/src/parser/interface.go:76 +0x2d7
github.com/DDP-Projekt/DDPLS/documents.(*DocumentState).reParseInContext(0xc000071b60, 0xc000692d80, 0xc000302db0)
	/home/bafto/source/repos/GoRepos/DDP-Projekt/DDPLS/documents/documents.go:58 +0x1b8
github.com/DDP-Projekt/DDPLS/documents.(*DocumentManager).reParse(0xc000411d30, {0xc00001d6e0, 0x2e}, 0x2e?)
	/home/bafto/source/repos/GoRepos/DDP-Projekt/DDPLS/documents/documents.go:111 +0x1a6
github.com/DDP-Projekt/DDPLS/documents.(*DocumentManager).Get(0xc000411d30, {0xc00001d3b0?, 0x16?})
	/home/bafto/source/repos/GoRepos/DDP-Projekt/DDPLS/documents/documents.go:123 +0x186
github.com/DDP-Projekt/DDPLS/handlers.CreateTextDocumentDidChange.func1(0xc0000db440, 0xc000692cc0)
	/home/bafto/source/repos/GoRepos/DDP-Projekt/DDPLS/handlers/sync.go:24 +0x5a
github.com/tliron/glsp/protocol_3_16.(*Handler).Handle(0xc000178b40, 0xc0000db440)
	/home/bafto/go/pkg/mod/github.com/bafto/glsp@v0.1.2-0.20230806091905-942e1aee0810/protocol_3_16/handler.go:320 +0x1567
github.com/tliron/glsp/server.(*Server).handle(0xc0000716e0, {0x721e68?, 0xc0000aa000}, 0xc00014ac60, 0xc0004b6ba0)
	/home/bafto/go/pkg/mod/github.com/bafto/glsp@v0.1.2-0.20230806091905-942e1aee0810/server/handle.go:46 +0x2b0
github.com/sourcegraph/jsonrpc2.(*HandlerWithErrorConfigurer).Handle(0xc000194040, {0x721e68, 0xc0000aa000}, 0xc00014ac60, 0xc0004b6ba0)
	/home/bafto/go/pkg/mod/github.com/sourcegraph/jsonrpc2@v0.2.0/handler_with_error.go:21 +0x63
github.com/sourcegraph/jsonrpc2.(*Conn).readMessages(0xc00014ac60, {0x721e68, 0xc0000aa000})
	/home/bafto/go/pkg/mod/github.com/sourcegraph/jsonrpc2@v0.2.0/conn.go:205 +0x26f
created by github.com/sourcegraph/jsonrpc2.NewConn
	/home/bafto/go/pkg/mod/github.com/sourcegraph/jsonrpc2@v0.2.0/conn.go:62 +0x2aa

goroutine 7 [running]:
github.com/DDP-Projekt/Kompilierer/src/parser.panic_wrapper()
	/home/bafto/go/pkg/mod/github.com/!d!d!p-!projekt/!kompilierer@v0.0.1-alpha.0.20231202103202-571eaedc3dde/src/parser/interface.go:91 +0x4d
panic({0x661c00, 0xc0001e86e0})
	/usr/local/go/src/runtime/panic.go:884 +0x213
github.com/DDP-Projekt/Kompilierer/src/parser.parser_panic_wrapper(0xc00067edd0)
	/home/bafto/go/pkg/mod/github.com/!d!d!p-!projekt/!kompilierer@v0.0.1-alpha.0.20231202103202-571eaedc3dde/src/parser/error.go:41 +0x148
panic({0x662e00, 0xc00023c360})
	/usr/local/go/src/runtime/panic.go:884 +0x213
github.com/DDP-Projekt/Kompilierer/src/ast/typechecker.(*Typechecker).VisitCastExpr(0xc000692f90, 0xc00072a900)
	/home/bafto/go/pkg/mod/github.com/!d!d!p-!projekt/!kompilierer@v0.0.1-alpha.0.20231202103202-571eaedc3dde/src/ast/typechecker/typechecker.go:425 +0xd34
github.com/DDP-Projekt/Kompilierer/src/ast.(*CastExpr).Accept(0x65dae0?, {0x725310?, 0xc000692f90?})
	/home/bafto/go/pkg/mod/github.com/!d!d!p-!projekt/!kompilierer@v0.0.1-alpha.0.20231202103202-571eaedc3dde/src/ast/ast.go:424 +0x2a
github.com/DDP-Projekt/Kompilierer/src/ast/typechecker.(*Typechecker).visit(...)
	/home/bafto/go/pkg/mod/github.com/!d!d!p-!projekt/!kompilierer@v0.0.1-alpha.0.20231202103202-571eaedc3dde/src/ast/typechecker/typechecker.go:49
github.com/DDP-Projekt/Kompilierer/src/ast/typechecker.(*Typechecker).Evaluate(...)
	/home/bafto/go/pkg/mod/github.com/!d!d!p-!projekt/!kompilierer@v0.0.1-alpha.0.20231202103202-571eaedc3dde/src/ast/typechecker/typechecker.go:54
github.com/DDP-Projekt/Kompilierer/src/ast/typechecker.(*Typechecker).VisitVarDecl(0xc000692f90, 0xc000448140)
	/home/bafto/go/pkg/mod/github.com/!d!d!p-!projekt/!kompilierer@v0.0.1-alpha.0.20231202103202-571eaedc3dde/src/ast/typechecker/typechecker.go:106 +0x75
github.com/DDP-Projekt/Kompilierer/src/ast.(*VarDecl).Accept(0xc000692f60?, {0x725310?, 0xc000692f90?})
	/home/bafto/go/pkg/mod/github.com/!d!d!p-!projekt/!kompilierer@v0.0.1-alpha.0.20231202103202-571eaedc3dde/src/ast/ast.go:194 +0x2d
github.com/DDP-Projekt/Kompilierer/src/ast/typechecker.(*Typechecker).VisitDeclStmt(0x67da40?, 0x0?)
	/home/bafto/go/pkg/mod/github.com/!d!d!p-!projekt/!kompilierer@v0.0.1-alpha.0.20231202103202-571eaedc3dde/src/ast/typechecker/typechecker.go:527 +0x2e
github.com/DDP-Projekt/Kompilierer/src/ast.(*DeclStmt).Accept(0x0?, {0x725310?, 0xc000692f90?})
	/home/bafto/go/pkg/mod/github.com/!d!d!p-!projekt/!kompilierer@v0.0.1-alpha.0.20231202103202-571eaedc3dde/src/ast/ast.go:580 +0x2a
github.com/DDP-Projekt/Kompilierer/src/ast/typechecker.(*Typechecker).TypecheckNode(...)
	/home/bafto/go/pkg/mod/github.com/!d!d!p-!projekt/!kompilierer@v0.0.1-alpha.0.20231202103202-571eaedc3dde/src/ast/typechecker/typechecker.go:44
github.com/DDP-Projekt/Kompilierer/src/parser.(*parser).checkStatement(0xc00067edd0, {0x7224f8, 0xc00068ebf0?})
	/home/bafto/go/pkg/mod/github.com/!d!d!p-!projekt/!kompilierer@v0.0.1-alpha.0.20231202103202-571eaedc3dde/src/parser/parser.go:262 +0xe6
github.com/DDP-Projekt/Kompilierer/src/parser.(*parser).checkedDeclaration(0xc00067edd0)
	/home/bafto/go/pkg/mod/github.com/!d!d!p-!projekt/!kompilierer@v0.0.1-alpha.0.20231202103202-571eaedc3dde/src/parser/parser.go:268 +0x3d
github.com/DDP-Projekt/Kompilierer/src/parser.(*parser).blockStatement(0xc00067edd0, 0xc00068ebd0)
	/home/bafto/go/pkg/mod/github.com/!d!d!p-!projekt/!kompilierer@v0.0.1-alpha.0.20231202103202-571eaedc3dde/src/parser/parser.go:1652 +0x2a6
github.com/DDP-Projekt/Kompilierer/src/parser.(*parser).whileStatement(0xc00067edd0)
	/home/bafto/go/pkg/mod/github.com/!d!d!p-!projekt/!kompilierer@v0.0.1-alpha.0.20231202103202-571eaedc3dde/src/parser/parser.go:1377 +0x5b1
github.com/DDP-Projekt/Kompilierer/src/parser.(*parser).statement(0xc00067edd0)
	/home/bafto/go/pkg/mod/github.com/!d!d!p-!projekt/!kompilierer@v0.0.1-alpha.0.20231202103202-571eaedc3dde/src/parser/parser.go:1047 +0x52b
github.com/DDP-Projekt/Kompilierer/src/parser.(*parser).declaration(0xc00067edd0)
	/home/bafto/go/pkg/mod/github.com/!d!d!p-!projekt/!kompilierer@v0.0.1-alpha.0.20231202103202-571eaedc3dde/src/parser/parser.go:308 +0x3aa
github.com/DDP-Projekt/Kompilierer/src/parser.(*parser).checkedDeclaration(0xc00067edd0)
	/home/bafto/go/pkg/mod/github.com/!d!d!p-!projekt/!kompilierer@v0.0.1-alpha.0.20231202103202-571eaedc3dde/src/parser/parser.go:266 +0x1e
github.com/DDP-Projekt/Kompilierer/src/parser.(*parser).blockStatement(0xc00067edd0, 0xc00068eb60)
	/home/bafto/go/pkg/mod/github.com/!d!d!p-!projekt/!kompilierer@v0.0.1-alpha.0.20231202103202-571eaedc3dde/src/parser/parser.go:1652 +0x2a6
github.com/DDP-Projekt/Kompilierer/src/parser.(*parser).whileStatement(0xc00067edd0)
	/home/bafto/go/pkg/mod/github.com/!d!d!p-!projekt/!kompilierer@v0.0.1-alpha.0.20231202103202-571eaedc3dde/src/parser/parser.go:1377 +0x5b1
github.com/DDP-Projekt/Kompilierer/src/parser.(*parser).statement(0xc00067edd0)
	/home/bafto/go/pkg/mod/github.com/!d!d!p-!projekt/!kompilierer@v0.0.1-alpha.0.20231202103202-571eaedc3dde/src/parser/parser.go:1047 +0x52b
github.com/DDP-Projekt/Kompilierer/src/parser.(*parser).declaration(0xc00067edd0)
	/home/bafto/go/pkg/mod/github.com/!d!d!p-!projekt/!kompilierer@v0.0.1-alpha.0.20231202103202-571eaedc3dde/src/parser/parser.go:308 +0x3aa
github.com/DDP-Projekt/Kompilierer/src/parser.(*parser).checkedDeclaration(0xc00067edd0)
	/home/bafto/go/pkg/mod/github.com/!d!d!p-!projekt/!kompilierer@v0.0.1-alpha.0.20231202103202-571eaedc3dde/src/parser/parser.go:266 +0x1e
github.com/DDP-Projekt/Kompilierer/src/parser.(*parser).parse(0xc00067edd0)
	/home/bafto/go/pkg/mod/github.com/!d!d!p-!projekt/!kompilierer@v0.0.1-alpha.0.20231202103202-571eaedc3dde/src/parser/parser.go:122 +0xa5
github.com/DDP-Projekt/Kompilierer/src/parser.Parse({{0xc00001d6e7, 0x27}, {0xc00053ca00, 0x21fc, 0x2500}, {0xc000598000, 0x5b7, 0x78e}, 0xc000692d80, 0xc000302db0})
	/home/bafto/go/pkg/mod/github.com/!d!d!p-!projekt/!kompilierer@v0.0.1-alpha.0.20231202103202-571eaedc3dde/src/parser/interface.go:76 +0x2d7
github.com/DDP-Projekt/DDPLS/documents.(*DocumentState).reParseInContext(0xc000071b60, 0xc000692d80, 0xc000302db0)
	/home/bafto/source/repos/GoRepos/DDP-Projekt/DDPLS/documents/documents.go:58 +0x1b8
github.com/DDP-Projekt/DDPLS/documents.(*DocumentManager).reParse(0xc000411d30, {0xc00001d6e0, 0x2e}, 0x2e?)
	/home/bafto/source/repos/GoRepos/DDP-Projekt/DDPLS/documents/documents.go:111 +0x1a6
github.com/DDP-Projekt/DDPLS/documents.(*DocumentManager).Get(0xc000411d30, {0xc00001d3b0?, 0x16?})
	/home/bafto/source/repos/GoRepos/DDP-Projekt/DDPLS/documents/documents.go:123 +0x186
github.com/DDP-Projekt/DDPLS/handlers.CreateTextDocumentDidChange.func1(0xc0000db440, 0xc000692cc0)
	/home/bafto/source/repos/GoRepos/DDP-Projekt/DDPLS/handlers/sync.go:24 +0x5a
github.com/tliron/glsp/protocol_3_16.(*Handler).Handle(0xc000178b40, 0xc0000db440)
	/home/bafto/go/pkg/mod/github.com/bafto/glsp@v0.1.2-0.20230806091905-942e1aee0810/protocol_3_16/handler.go:320 +0x1567
github.com/tliron/glsp/server.(*Server).handle(0xc0000716e0, {0x721e68?, 0xc0000aa000}, 0xc00014ac60, 0xc0004b6ba0)
	/home/bafto/go/pkg/mod/github.com/bafto/glsp@v0.1.2-0.20230806091905-942e1aee0810/server/handle.go:46 +0x2b0
github.com/sourcegraph/jsonrpc2.(*HandlerWithErrorConfigurer).Handle(0xc000194040, {0x721e68, 0xc0000aa000}, 0xc00014ac60, 0xc0004b6ba0)
	/home/bafto/go/pkg/mod/github.com/sourcegraph/jsonrpc2@v0.2.0/handler_with_error.go:21 +0x63
github.com/sourcegraph/jsonrpc2.(*Conn).readMessages(0xc00014ac60, {0x721e68, 0xc0000aa000})
	/home/bafto/go/pkg/mod/github.com/sourcegraph/jsonrpc2@v0.2.0/conn.go:205 +0x26f
created by github.com/sourcegraph/jsonrpc2.NewConn
	/home/bafto/go/pkg/mod/github.com/sourcegraph/jsonrpc2@v0.2.0/conn.go:62 +0x2aa
[Error - 11:02:12 AM] Connection to server got closed. Server will not be restarted.
</p>
</details>

**Comment by Magi3r** [comment]
Genauer tritt das Problem schon auf, sobald das Keyword `als` geschrieben wurde, nicht erst beim Schreiben des Typs `Text`.
