### ISSUE TITLE
Crash bei nicht-Identifier Zeichen als Funktionsparameter

### ISSUE THREAD

**Issue by NotLe0n** [DDP-Projekt/DDPLS#4]
# Language Server Absturz
Der Language Server stürzt ab wenn man einer Funktion einen nicht-Identifier Zeichen (also nicht [a-zA-ZäÄöÖüÜß]) als Parameter gibt.

## Fehlermeldung und Stack trace
```
panic: runtime error: index out of range [5] with length 5

goroutine 15 [running]:
github.com/DDP-Projekt/DDPLS/helper.GetRangeLength({{0xa30a20?, 0xc0002e3ab8?}, {0x1?, 0xc0005c24e0?}}, 0xc00047c4e0?)
	D:/Hendrik/source/OtherLanguages/GoRepos/DDP-Projekt/DDPLS/helper/protocol_helper.go:33 +0x114
github.com/DDP-Projekt/DDPLS/handlers.(*semanticTokenizer).VisitFuncCall(0xc00006b8c0, 0xc0005f2cf0)
	D:/Hendrik/source/OtherLanguages/GoRepos/DDP-Projekt/DDPLS/handlers/semanticHighlighting.go:190 +0x52f
github.com/DDP-Projekt/Kompilierer/src/ast.(*helperVisitor).VisitFuncCall(0xc0002e3aa0, 0xc0005f2cf0)
	C:/Users/Hendrik/Go/pkg/mod/github.com/!d!d!p-!projekt/!kompilierer@v0.2.0-alpha/src/ast/helper_visitor.go:252 +0x5f
github.com/DDP-Projekt/Kompilierer/src/ast.(*FuncCall).Accept(0x250fb1f0900?, {0xb0efe0?, 0xc0002e3aa0?})
	C:/Users/Hendrik/Go/pkg/mod/github.com/!d!d!p-!projekt/!kompilierer@v0.2.0-alpha/src/ast/ast.go:426 +0x27
github.com/DDP-Projekt/Kompilierer/src/ast.(*helperVisitor).visit(0xc0002e3aa0, {0x250fb1f0900, 0xc0005f2cf0})
	C:/Users/Hendrik/Go/pkg/mod/github.com/!d!d!p-!projekt/!kompilierer@v0.2.0-alpha/src/ast/helper_visitor.go:83 +0xbf
github.com/DDP-Projekt/Kompilierer/src/ast.(*helperVisitor).visitChildren(0x80a67a?, 0xc0?, {0xc00053b9f8?, 0x1, 0x18?})
	C:/Users/Hendrik/Go/pkg/mod/github.com/!d!d!p-!projekt/!kompilierer@v0.2.0-alpha/src/ast/helper_visitor.go:96 +0x7e
github.com/DDP-Projekt/Kompilierer/src/ast.(*helperVisitor).VisitExprStmt(0xc0002e3aa0, 0xc0005c8ce0)
	C:/Users/Hendrik/Go/pkg/mod/github.com/!d!d!p-!projekt/!kompilierer@v0.2.0-alpha/src/ast/helper_visitor.go:282 +0x9b
github.com/DDP-Projekt/Kompilierer/src/ast.(*ExprStmt).Accept(0x250fb1f08c8?, {0xb0efe0?, 0xc0002e3aa0?})
	C:/Users/Hendrik/Go/pkg/mod/github.com/!d!d!p-!projekt/!kompilierer@v0.2.0-alpha/src/ast/ast.go:581 +0x24
github.com/DDP-Projekt/Kompilierer/src/ast.(*helperVisitor).visit(0xc0002e3aa0, {0x250fb1f08c8, 0xc0005c8ce0})
	C:/Users/Hendrik/Go/pkg/mod/github.com/!d!d!p-!projekt/!kompilierer@v0.2.0-alpha/src/ast/helper_visitor.go:83 +0xbf
github.com/DDP-Projekt/Kompilierer/src/ast.VisitAst(0xc00006ad00, {0xb0a5c0?, 0xc00006b8c0})
	C:/Users/Hendrik/Go/pkg/mod/github.com/!d!d!p-!projekt/!kompilierer@v0.2.0-alpha/src/ast/helper_visitor.go:47 +0x15a
github.com/DDP-Projekt/DDPLS/ddpls.NewDDPLS.CreateTextDocumentSemanticTokensFull.func6(0xc00001ad90?, 0xc000213960)
	D:/Hendrik/source/OtherLanguages/GoRepos/DDP-Projekt/DDPLS/handlers/semanticHighlighting.go:31 +0xc5
github.com/tliron/glsp/protocol_3_16.(*Handler).Handle(0xc0003a0d80, 0xc00006b880)
	C:/Users/Hendrik/Go/pkg/mod/github.com/tliron/glsp@v0.2.1/protocol_3_16/handler.go:662 +0x3802
github.com/tliron/glsp/server.(*Server).handle(0xc0007eb8c0, {0xb0bfc0?, 0xcfbfa0}, 0xc00039cab0, 0xc0007ebd40)
	C:/Users/Hendrik/Go/pkg/mod/github.com/tliron/glsp@v0.2.1/server/handle.go:46 +0x28f
github.com/sourcegraph/jsonrpc2.(*HandlerWithErrorConfigurer).Handle(0xc00043f070, {0xb0bfc0, 0xcfbfa0}, 0xc00039cab0, 0xc0007ebd40)
	C:/Users/Hendrik/Go/pkg/mod/github.com/sourcegraph/jsonrpc2@v0.2.0/handler_with_error.go:21 +0x57
github.com/sourcegraph/jsonrpc2.(*Conn).readMessages(0xc00039cab0, {0xb0bfc0, 0xcfbfa0})
	C:/Users/Hendrik/Go/pkg/mod/github.com/sourcegraph/jsonrpc2@v0.2.0/conn.go:205 +0x267
created by github.com/sourcegraph/jsonrpc2.NewConn in goroutine 1
	C:/Users/Hendrik/Go/pkg/mod/github.com/sourcegraph/jsonrpc2@v0.2.0/conn.go:62 +0x236
```

## Reproduzierung
```
Die Funktion Name mit dem Parameter x vom Typ Zahl, gibt nichts zurück, macht:
Und kann so benutzt werden:
    "Test <x>"

Test $.
```

**Comment by bafto** [comment]
fixed in [5e5cb07](https://github.com/DDP-Projekt/Kompilierer/commit/5e5cb0739b1ff3dda8b3b43ae498146136197ef0)
Sobald die Kompilierer Abhängigkeit das nächste Mal geupdated wird ist dieses Problem ebenfalls behoben.
